export const siteDate = '2026-09-14';
export const siteUrl = 'https://relay.bobochang.cn';
export const repo = 'https://github.com/can4hou6joeng4/Watch';
export const maintainer = { name: 'can4hou6joeng4', url: 'https://bobochang.cn', github: 'https://github.com/can4hou6joeng4', locality: 'Guangzhou' };
export const locales = { zh: { path: '/', hreflang: 'zh-CN', ogLocale: 'zh_CN', ogImage: '/og.png' }, en: { path: '/en/', hreflang: 'en', ogLocale: 'en_US', ogImage: '/og-en.png' } };
export const defaultLocale = 'en';
export const siteVerification = { 'baidu-site-verification': 'codeva-W4z09gkNmy' };
export const agents = [
  { id: 'claude', label: 'Claude Code' }, { id: 'codex', label: 'OpenAI Codex' },
  { id: 'opencode', label: 'OpenCode' }, { id: 'kimi', label: 'Kimi CLI' }, { id: 'pi', label: 'Pi' },
];
export const samples = [
  { id: '11111111-1111-4111-8111-111111111111', provider: 'claude', cwd: '/Users/dev/projects/example-api', messages: 24, tools: 8 },
  { id: 'ses_demo_opencode', provider: 'opencode', cwd: '/Users/dev/code/finance-core', messages: 42, tools: 15 },
  { id: 'demo-kimi-202609', provider: 'kimi', cwd: '/Users/dev/workspace/gateway-service', messages: 16, tools: 3 },
];
export const evidence = [
  { date: '2026-09-07', file: 'codex-native-2026-09-07-official.json' },
  { date: '2026-09-08', file: 'codex-desktop-project-first-gui-2026-09-08.json' },
  { date: '2026-09-10', file: 'watch-codex-import-tauri-native-2026-09-10.json' },
];
export const content = {
  zh: {
    antigravityTitle: 'Antigravity CLI：同产品恢复与导入', antigravityIntro: '官方入口已调研，Watch 接力尚未接入。以下是 Antigravity 自身的操作，不是 Watch 转换命令。', antigravityStatus: '官方有依据 / Watch 未验收', antigravityItems: [
      ['恢复指定 CLI 会话', 'agy --conversation <conversation-id>', '仅恢复已有的 Antigravity CLI 会话 ID，不是把 Claude、Codex 或桌面会话导入 CLI。'],
      ['恢复当前目录最近会话', 'agy -c', '按当前工作目录查找最近会话；记录缺失或已删除时可能新建会话。因此不能将它当作无副作用的状态探测。'],
      ['从 Antigravity 2.0 导入', '/resume', '在 CLI 的会话选择器中切至 Antigravity 页签，选择桌面会话并二次确认。官方描述为克隆历史、上下文与工具轨迹；Watch 尚未原生验收，也没有外部 Agent 导入协议。'],
    ], antigravityDocs: '官方恢复与导入文档', heroLabel: 'AGENTRELAY / 本地会话接力', h1: 'Watch · 值更', h1Sub: '本地会话接力工具', ogAlt: 'Watch · 值更：本地 AI 编程 Agent 会话接力工具', siteName: 'Watch · 值更', heroDetail: 'Claude Code 限额、上下文满了或排查停滞时，带上已有记录与工作目录，切换到 Codex、OpenCode、Kimi 或 Pi 继续。', start: '从源码开始', explore: '体验接力', scroll: '探索会话接力',
    lang: 'zh-CN', loaded: '样本已载入', title: 'Watch · 值更 | AgentRelay 本地会话接力', description: 'Watch（AgentRelay）是本地 AI 编程会话接力工具：Claude Code 限额或额度用完后，把已有会话记录切换到 Codex、OpenCode、Kimi 或 Pi 继续，核对工作目录与路径限制。',
    workspace: '工作空间', resource: '项目资源', demo: '接力演示', mechanisms: '核心机制', compatibility: '支持路径', quickstart: '从源码上手', evidence: '验收证据', faq: '常见问题', repo: '源代码', docs: '项目文档', local: '本地会话工具', language: 'English', skip: '跳至内容', menu: '打开导航',
    intro: '换一个编程工具，继续同一项工作。', introDetail: '读取已有会话记录，核对工作目录，再选择目标 Agent。', demoBadge: '合成演示 · 无真实写入', online: '交互预览', stepLabels: ['来源会话', '上下文核验', '接力目标', '交付结果'],
    source: '来源会话', sample: '示例场景', sampleNames: ['Claude Code · 切换工具', 'OpenCode · 继续排查', 'Kimi CLI · 历史接力'], sessionId: '来源会话 ID', sourceAgent: '来源 Agent', cwd: '工作目录', messages: '消息', tools: '工具调用', context: '上下文摘录', user: '用户', assistant: '助手', userPrompt: '检查 API 重试流程，保留此前结论与失败尝试。', assistantReply: '已确认工作目录和重试边界；下一步补充错误处理回归。',
    target: '接力目标', route: '接力方式', official: '官方桌面导入', conversion: '基础 CLI 转换', resume: '原会话恢复', delivery: '交付方式', terminal: '终端命令', desktop: 'Codex Desktop', preview: '预览接力', confirm: '模拟确认导入', open: '模拟打开目标', reset: '重置演示', result: '接力结果', logs: '流程记录', structure: '事件示意', waiting: '等待预览', prepared: '计划已准备', imported: '演示导入完成', opened: '演示打开完成', unknown: '未知示例 ID', copy: '复制命令', copied: '已复制', copyError: '复制失败，请手动选择命令',
    demoNotice: '仅使用合成记录，不读取本机、不写入 Agent、不启动客户端。', media: '真实运行画面', mediaIntro: '在隔离环境用合成会话生成：GIF 是 CLI 的真实输出按原时序回放，截图是桌面端浏览器预览的合成演示。它们展示程序真实行为，不是原生验收证据。', mediaItems: [['CLI：Claude Code → OpenCode', 'status → sessions → switch opencode → status，路径已改写为 ~ 便于阅读；写入的是临时 OpenCode 库。'], ['桌面端：Claude Code → Codex Desktop 官方导入', '载入演示 → 预览导入计划 → 模拟确认导入；右上角 DEMO 标记为真实渲染。亮色主题截图，暗色见仓库 assets。']], mediaMore: '生成脚本与边界说明', officialWarning: '项目须先存在；工具调用与结果可能降级为文本。模型继续未纳入限定通过范围。', baselineWarning: '基础适配器已实现；不同目标可能丢失或降级部分内容，不代表该方向已通过原生验收。', unknownNotice: '当前 ID 不属于演示样本。真实会话请在 Watch 桌面端操作。', planLabel: '演示计划', targetId: '目标会话 ID', commandPending: '确认后生成目标恢复命令', logReady: '合成记录已载入，等待预览。', logPreview: '演示：已核对来源 ID 与 cwd，生成接力计划。未写入真实会话。', logConfirm: '演示：目标记录已生成。未调用导入接口；不代表真实客户端验收。', logOpen: '演示：打开动作已模拟。未启动终端或桌面端，也未请求模型。', eventSource: '来源事件（示意）', eventTarget: '目标表示（示意，非原生 schema）',
    mechanismIntro: '每条接力路径有自己的保护边界，不将局部校验包装成全局保证。桌面端提供会话接力、接力记录、支持路径、设置四个视图，外观支持亮色、暗色与跟随系统。',
    mechanismItems: [
      ['search', '定位来源与工作目录', '根据原生会话 ID 查找记录，保留实际 cwd。不会自动把已有 Worktree 改为主仓库目录。'],
      ['shield-check', '官方导入独立确认', 'Codex 路径绑定目标目录与配置，使用执行日志与持久锁。结果不确定时保留计划，只查询状态。'],
      ['file-text', '格式转换与降级', '按目标格式转录已记录的消息与事件。不同工具保留程度不同；内部 round-trip 不等于原生继续验收。'],
      ['terminal', '转入与打开分离', '导入已成功但客户端打开失败时，仅重试打开。终端启动失败会尝试复制命令，不重复转入。'],
    ],
    compatibilityIntro: '按来源、方向、平台与版本核验。安装检测不是兼容性证明。', all: '全部路径', limited: '限定验收', pending: '待验收 / 未接入', path: '接力路径', method: '入口', scope: '证据与限制', status: '状态',
    paths: [
      ['Claude Code → Codex Desktop', '官方导入', 'macOS arm64 合成样本：项目列表、prepare / confirm / 两次独立打开限定通过；工具记录可转为文本，模型继续仍受限。', 'limited', '限定验收'],
      ['Claude / Codex / OpenCode / Kimi / Pi', '基础 CLI 适配器', '读取、转换和恢复入口已实现。不是所有组合、平台、内容样本和版本都已通过原生验收。', 'pending', '逐方向验收'],
      ['OpenCode Web / TUI 官方增强', '官方 JSON 实验', '1.18.29 隔离历史可见与目标模型有效性已通过；单次模型继续返回 provider 429，未作为新的默认入口。', 'pending', '未接入增强'],
      ['Antigravity 2.0 → Antigravity CLI', '同产品交互式 picker', '官方 /resume 的 Antigravity 页签可在二次确认后导入；--conversation 只恢复既有 CLI 会话。Watch 尚无适配器与原生验收，不是其他 Agent → Antigravity。', 'pending', '未接入'],
      ['Claude Desktop Code / 其他入口', '官方入口调研', '尚无 Watch 完整路径验收，不增加默认目标入口。Grok CLI 适配器保留，但没有桌面目标卡。', 'pending', '未接入'],
    ],
    quickIntro: '从仓库运行 CLI 或构建桌面端。需要仓库访问权限，未发布 npm 全局包。', requirements: 'Node ≥ 22.13 · 桌面构建另需 Rust / Tauri 环境', cli: 'CLI', desktopBuild: '桌面端', copyAll: '复制整组命令', troubleshooting: '出现 tsx 缺失时先运行 npm install；node:sqlite 错误需核对 Node 版本。',
    evidenceIntro: '以下是仓库历史验收，不是此次设计重构的新客户端验收。', evidenceTitles: ['官方导入原生读取与恢复', '项目先建与 Desktop 列表可见', 'Watch Tauri 预览、确认与独立打开'], evidenceDetails: ['Codex CLI 0.153.4 / macOS arm64；工具记录降级为文本，未做桌面 UI 或模型继续。', 'ChatGPT Desktop 26.901.51231；合成样本在项目列表可见，未做模型继续。', 'ChatGPT Desktop 26.903.61454；合成样本两次进入同一目标，只有一个导入计划。模型继续仍不属于通过范围。'], faqs: [
      ['Claude Code 限额或额度用完后，怎么继续手头的任务？', '在 Watch 桌面端输入来源会话 ID，核对实际工作目录，选择目标 Agent。Claude → Codex 先显示官方项目先建的导入预览，明确确认后才写入，再独立打开目标会话；其他目标使用已有 CLI 适配器。Watch 不绕过限额，也不迁移代码，转入的是已有会话记录。'],
      ['怎么把 Claude Code 的会话转到 Codex 继续（会话迁移 / 切换）？', '两种入口：桌面端选择来源会话后点 OpenAI Codex 卡片，走官方单会话导入的 prepare → confirm → 打开；或用 CLI watch import-codex prepare <claude-id> --cwd <项目> --desktop-project --experimental，再 confirm。前提是该项目已在 Codex Desktop 中存在。工具调用记录在 Codex 侧可能变为文本，模型续写未纳入验收范围。'],
      ['Claude Code 上下文满了怎么办，Watch 能压缩上下文吗？', '不能。压缩或清空上下文是 Claude Code 自己的 /compact 与 /clear。Watch 做的是把已保存的会话记录整体转入另一个 Agent，目标会话从这些记录开始，原会话不变。上下文是否装得下取决于目标工具的窗口大小。'],
      ['Claude Code、Codex、OpenCode 的历史对话记录在哪里，怎么恢复上次对话？', 'Claude Code 在 ~/.claude/projects/<按目录编码>/<会话 id>.jsonl，用 claude --resume <id> 恢复；Codex 在 ~/.codex/sessions/年/月/日/rollout-*.jsonl，用 codex resume <id>；OpenCode 在 ~/.local/share/opencode/opencode.db，用 opencode -s <id>。Watch 的「会话接力」按会话 id 反查这些位置并显示所属工作目录，「接力记录」列出同一目录的链式接力历史。'],
      ['Claude Code 和 Codex 对比之后想两个都用，切换时怎么不丢上下文？', 'Watch 不评测哪家更好。两家都装好并认证后，用 Watch 在两者之间接力：Claude → Codex 走官方导入预览，Codex → Claude 走 CLI 适配器转换；两条路径都保留工作目录。不同格式可能降级部分事件，结果会列出降级项。'],
      ['会话会经过 Watch 的云端服务器吗？', 'Watch 是本地会话工具，不提供自己的中继服务器。部分原生会话创建路径会调用目标 CLI，可能联网；目标 Agent 继续调用模型时，也按它自身的服务与隐私规则通信。本地转换不等于全流程离线。'],
      ['可以保证无损转换或零写入风险吗？', '不能。新建或整文件替换有原子写和反解校验，部分追加路径的保护范围不同。Codex 官方路径使用独立执行日志、目标锁与读后验证；完整边界见架构文档。'],
    ], fleet: 'The Fleet · 船队', license: 'MIT License', updated: '页面更新 ' + siteDate, footerNote: 'Relieve the watch. The voyage never stalls.', notFound: '页面不存在', notFoundText: '这个地址没有对应页面。', back: '返回会话演示', otherLanguage: 'English homepage',
  },
  en: {
    antigravityTitle: 'Antigravity CLI: same-product resume and import', antigravityIntro: 'Official entry points reviewed; not integrated into Watch. These are Antigravity operations, not Watch conversion commands.', antigravityStatus: 'Officially documented / Not Watch-validated', antigravityItems: [
      ['Resume a specific CLI conversation', 'agy --conversation <conversation-id>', 'Resumes an existing Antigravity CLI conversation ID. It is not an importer for Claude, Codex or desktop conversations.'],
      ['Continue the latest workspace conversation', 'agy -c', 'Looks up the latest conversation for the current working directory. Missing or deleted history can start a new conversation, so this is not a side-effect-free status check.'],
      ['Import from Antigravity 2.0', '/resume', 'Switch to the Antigravity tab in the CLI session picker, select a desktop conversation and confirm the import. Official documentation describes cloned history, context and tool trajectories. Watch has not natively validated it and has no external-agent import contract.'],
    ], antigravityDocs: 'Official resume and import documentation', heroLabel: 'AGENTRELAY / LOCAL SESSION HANDOFF', h1: 'Watch', h1Sub: 'Local session handoff for coding agents', ogAlt: 'Watch: local session handoff tool for AI coding agents', siteName: 'Watch · 值更', heroDetail: 'Hit a Claude Code limit, a full context window or a stuck investigation? Carry the saved history and working directory into Codex, OpenCode, Kimi or Pi and keep going.', start: 'Run from source', explore: 'Explore handoff', scroll: 'Explore session handoff',
    lang: 'en', loaded: 'Source loaded', title: 'Watch | AgentRelay Local Session Handoff', description: 'Watch (AgentRelay): local session handoff for AI coding agents. When Claude Code hits its limit, switch to Codex, OpenCode, Kimi or Pi and resume the saved session.',
    workspace: 'WORKSPACE', resource: 'RESOURCES', demo: 'Session Handoff', mechanisms: 'Core Mechanisms', compatibility: 'Supported Routes', quickstart: 'Run From Source', evidence: 'Validation Records', faq: 'Questions', repo: 'Source Code', docs: 'Documentation', local: 'Local session tool', language: '中文', skip: 'Skip to content', menu: 'Open navigation',
    intro: 'Another coding tool. The same work.', introDetail: 'Read saved history, check the working directory, then choose a target agent.', demoBadge: 'SYNTHETIC DEMO / NO WRITES', online: 'Interactive preview', stepLabels: ['Source session', 'Check context', 'Target agent', 'Delivery result'],
    source: 'Source Session', sample: 'Sample scenario', sampleNames: ['Claude Code · Switch tools', 'OpenCode · Continue debugging', 'Kimi CLI · Handoff history'], sessionId: 'Source session ID', sourceAgent: 'Source agent', cwd: 'Working directory', messages: 'Messages', tools: 'Tool calls', context: 'Context Excerpt', user: 'USER', assistant: 'AGENT', userPrompt: 'Check the API retry flow and retain earlier conclusions and failed attempts.', assistantReply: 'Confirmed the working directory and retry boundary. Next: error-handling regressions.',
    target: 'Target Agent', route: 'Handoff route', official: 'Official desktop import', conversion: 'Baseline CLI conversion', resume: 'Resume original session', delivery: 'Delivery', terminal: 'Terminal command', desktop: 'Codex Desktop', preview: 'Preview handoff', confirm: 'Simulate confirmation', open: 'Simulate opening', reset: 'Reset demo', result: 'Handoff Result', logs: 'Workflow log', structure: 'Event illustration', waiting: 'Awaiting preview', prepared: 'Plan prepared', imported: 'Demo import complete', opened: 'Demo open complete', unknown: 'Unknown sample ID', copy: 'Copy command', copied: 'Copied', copyError: 'Copy failed. Select the command manually.',
    demoNotice: 'Synthetic records only. No local reads, agent writes, client launches or model requests.', media: 'Real program output', mediaIntro: 'Generated from synthetic sessions in an isolated environment: the GIF replays real CLI output with its original timing; the screenshot is the desktop browser preview in synthetic demo mode. They show real behaviour, not native acceptance evidence.', mediaItems: [['CLI: Claude Code → OpenCode', 'status → sessions → switch opencode → status; paths rewritten to ~ for readability; writes go to a temporary OpenCode store.'], ['Desktop: Claude Code → Codex Desktop official import', 'Load demo → preview plan → simulated confirmation; the DEMO badge is rendered by the app. Light theme shown; dark theme in assets.']], mediaMore: 'Generator scripts and limits', officialWarning: 'The desktop project must exist first. Tool calls and results may become text. Model continuation is outside the limited pass.', baselineWarning: 'Baseline adapters exist. Some content may be lost or degraded; this does not prove native acceptance for this route.', unknownNotice: 'This ID is not a demo sample. Use the Watch desktop app for real sessions.', planLabel: 'Demo plan', targetId: 'Target session ID', commandPending: 'The target resume command appears after confirmation', logReady: 'Synthetic source loaded. Awaiting preview.', logPreview: 'Demo: checked the source ID and cwd; prepared a handoff plan. No real writes.', logConfirm: 'Demo: generated a target record. No import API was called; this is not native-client validation.', logOpen: 'Demo: simulated opening. No terminal or desktop was launched; no model was requested.', eventSource: 'Source event (illustration)', eventTarget: 'Target representation (illustration, not native schema)',
    mechanismIntro: 'Protection is route-specific. A narrow check is not a universal safety guarantee. The desktop app has four views (session handoff, handoff history, supported routes, settings) with light, dark and system appearance.',
    mechanismItems: [
      ['search', 'Locate the source and cwd', 'Find stored records by native session ID and preserve the actual cwd. Existing worktrees are not silently replaced with the repository root.'],
      ['shield-check', 'Confirm official imports', 'The Codex route binds the target directory and configuration, with an execution journal and persistent lock. Uncertain outcomes are queried, not blindly resubmitted.'],
      ['file-text', 'Expose format limitations', 'Transfer recorded messages and events into the target format. Preservation varies; an internal round-trip is not proof of native continuation.'],
      ['terminal', 'Separate import from opening', 'If opening fails after import, retry opening only. A failed terminal launch falls back to copying the command without another transfer.'],
    ],
    compatibilityIntro: 'Validate by source, direction, platform and version. CLI discovery is not compatibility evidence.', all: 'All routes', limited: 'Limited validation', pending: 'Pending / Not integrated', path: 'Handoff route', method: 'Entry point', scope: 'Evidence and limitations', status: 'Status',
    paths: [
      ['Claude Code → Codex Desktop', 'Official import', 'macOS arm64 synthetic sample: project listing, prepare / confirm and two independent opens passed within scope. Tool records may become text; model continuation remains limited.', 'limited', 'Limited pass'],
      ['Claude / Codex / OpenCode / Kimi / Pi', 'Baseline CLI adapters', 'Reading, conversion and resume entry points exist. Native acceptance is not proven for every combination, platform, content sample or version.', 'pending', 'Per-route validation'],
      ['OpenCode Web / TUI enhancement', 'Official JSON experiment', '1.18.29 isolated history visibility and valid target model passed. One continuation request returned provider 429; not integrated as a new default entry.', 'pending', 'Not integrated'],
      ['Antigravity 2.0 → Antigravity CLI', 'Same-product interactive picker', 'The official /resume Antigravity tab imports after a second confirmation; --conversation only resumes existing CLI history. Watch has no adapter or native acceptance. This is not other-agent → Antigravity import.', 'pending', 'Not integrated'],
      ['Claude Desktop Code / Other entry points', 'Official entry research', 'No complete Watch route acceptance; no new default targets. The Grok CLI adapter remains, without a desktop target card.', 'pending', 'Not integrated'],
    ],
    quickIntro: 'Run the CLI from the repository or build the desktop app. Repository access is required. No global npm package is published.', requirements: 'Node ≥ 22.13 · Desktop builds also require Rust / Tauri', cli: 'CLI', desktopBuild: 'Desktop', copyAll: 'Copy command group', troubleshooting: 'Missing tsx? Run npm install first. A node:sqlite error requires checking the Node version.',
    evidenceIntro: 'Historical repository validation, not new native-client acceptance from this redesign.', evidenceTitles: ['Official import: native read and resume', 'Project-first import and Desktop listing', 'Watch Tauri: preview, confirm and independent open'], evidenceDetails: ['Codex CLI 0.153.4 / macOS arm64. Tool records became text; no desktop UI or model continuation.', 'ChatGPT Desktop 26.901.51231. Synthetic sample visible in the project list; no model continuation.', 'ChatGPT Desktop 26.903.61454. Two opens reached the same synthetic target with one import plan. Model continuation remains outside the pass.'], faqs: [
      ['Claude Code hit its limit mid-task. How do I continue?', 'Enter the source session ID in Watch, check the detected working directory and pick a target agent. Claude → Codex shows the official project-first import preview and writes only after you confirm, then opens the target separately; other targets use the existing CLI adapters. Watch does not bypass usage limits and does not move code; it transfers the saved session record.'],
      ['How do I switch from Claude Code to Codex and resume the same session?', 'Two entry points: in the desktop app select the source session and click the OpenAI Codex card (official single-session import: prepare → confirm → open), or run watch import-codex prepare <claude-id> --cwd <project> --desktop-project --experimental followed by confirm. The project must already exist in Codex Desktop. Tool records may become text on the Codex side and model continuation is outside the validated scope.'],
      ['My Claude Code context window is full. Does Watch compact it?', 'No. Compacting or clearing context is Claude Code\'s own /compact and /clear. Watch moves the saved session record as a whole into another agent; the target session starts from that record and the original session is untouched. Whether it fits depends on the target tool\'s context window.'],
      ['Where are Claude Code, Codex and OpenCode session files, and how do I resume a previous conversation?', 'Claude Code: ~/.claude/projects/<encoded-cwd>/<session-id>.jsonl, resume with claude --resume <id>. Codex: ~/.codex/sessions/YYYY/MM/DD/rollout-*.jsonl, resume with codex resume <id>. OpenCode: ~/.local/share/opencode/opencode.db, resume with opencode -s <id>. Watch looks these up by session ID, shows the owning working directory, and lists chained handoffs for that directory under Handoff History.'],
      ['I use both Claude Code and Codex. How do I move between them without losing context?', 'Watch does not rank the two. With both installed and authenticated, hand sessions across: Claude → Codex uses the official import preview, Codex → Claude uses the CLI adapter conversion; both keep the working directory. Some events may be degraded between formats, and the result lists what was degraded.'],
      ['Does history pass through a Watch cloud server?', 'Watch has no relay server of its own. Some native session creation routes invoke the target CLI and may access its network services. Model continuation also follows that service\u2019s privacy and model rules. Local conversion does not mean an entirely offline workflow.'],
      ['Is conversion lossless or risk-free?', 'No. New files and whole-file replacements have atomic writes and parse-back checks, while some append paths have different protections. Official Codex imports use their own journal, target lock and read-back verification. See the architecture for exact boundaries.'],
    ], fleet: 'THE FLEET', license: 'MIT License', updated: 'Page updated ' + siteDate, footerNote: 'Relieve the watch. The voyage never stalls.', notFound: 'Page not found', notFoundText: 'There is no page at this address.', back: 'Return to the session demo', otherLanguage: '中文版首页',
  },
};
