import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { agents, content, defaultLocale, evidence, locales, maintainer, repo, samples, siteDate, siteUrl, siteVerification } from './lib/site-content.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const site = path.join(root, 'site');
const esc = (text) => String(text).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const icon = (name) => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><use href="/icons.svg#${name}"></use></svg>`;
const link = (url, label) => `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}${icon('arrow-up-right')}</a>`;
const commands = {
  cli: ['git clone https://github.com/can4hou6joeng4/Watch.git', 'cd Watch && npm install', 'npm run watch -- status --json', 'npm run watch -- import-codex prepare <claude-id> --cwd /abs/project --desktop-project --experimental --json'],
  desktop: ['npm --prefix desktop install', 'npm run desktop:dev', 'cd desktop && npx tauri build'],
};
const localeUrl = (locale) => `${siteUrl}${locales[locale].path}`;
const otherLocale = (locale) => Object.keys(locales).find((key) => key !== locale);
const hreflangLinks = () => [...Object.entries(locales).map(([key, meta]) => `<link rel="alternate" hreflang="${meta.hreflang}" href="${localeUrl(key)}">`), `<link rel="alternate" hreflang="x-default" href="${localeUrl(defaultLocale)}">`].join('');
function renderPage(locale) {
  const t = content[locale];
  const meta = locales[locale];
  const canonical = localeUrl(locale);
  const other = otherLocale(locale);
  const ogImage = `${siteUrl}${meta.ogImage}`;
  const person = { '@type': 'Person', '@id': `${siteUrl}/#maintainer`, name: maintainer.name, url: maintainer.url, jobTitle: 'Developer', address: { '@type': 'PostalAddress', addressLocality: maintainer.locality, addressCountry: 'CN' }, sameAs: [maintainer.github, `${maintainer.github}/Homeport`] };
  const nav = [['simulator', 'workflow', t.demo], ['features', 'layers', t.mechanisms], ['compatibility', 'shield-check', t.compatibility], ['quickstart', 'terminal', t.quickstart], ['evidence', 'history', t.evidence], ['faq', 'circle-help', t.faq]];
  const jsonld = { '@context': 'https://schema.org', '@graph': [
    person,
    { '@type': 'WebSite', '@id': `${siteUrl}/#website`, url: `${siteUrl}/`, name: 'Watch', alternateName: ['AgentRelay', '值更', 'Watch · 值更'], inLanguage: Object.values(locales).map((item) => item.hreflang), publisher: { '@id': `${siteUrl}/#maintainer` } },
    { '@type': 'WebPage', '@id': `${canonical}#webpage`, url: canonical, name: t.title, description: t.description, inLanguage: t.lang, datePublished: '2026-09-12', dateModified: siteDate, isPartOf: { '@id': `${siteUrl}/#website` }, about: { '@id': `${siteUrl}/#app` }, mainEntity: { '@id': `${siteUrl}/#app` }, hasPart: [{ '@id': `${canonical}#faq` }], primaryImageOfPage: { '@type': 'ImageObject', url: ogImage, width: 1200, height: 630 }, ...(locale === defaultLocale ? {} : { translationOfWork: { '@id': `${localeUrl(defaultLocale)}#webpage` } }) },
    { '@type': 'SoftwareApplication', '@id': `${siteUrl}/#app`, name: 'Watch', alternateName: ['AgentRelay', '值更', 'Watch · 值更'], url: `${siteUrl}/`, description: t.description, inLanguage: t.lang, applicationCategory: 'DeveloperApplication', applicationSubCategory: 'AI coding agent session handoff', operatingSystem: 'macOS', softwareVersion: '0.1.1', softwareRequirements: 'Node.js >= 22.13 (node:sqlite)', datePublished: '2026-09-12', dateModified: siteDate, isAccessibleForFree: true, license: `${repo}/blob/main/LICENSE`, downloadUrl: `${repo}/releases`, offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, author: { '@id': `${siteUrl}/#maintainer` }, publisher: { '@id': `${siteUrl}/#maintainer` }, image: ogImage },
    { '@type': 'SoftwareSourceCode', '@id': `${siteUrl}/#source`, name: 'Watch', codeRepository: repo, programmingLanguage: ['TypeScript', 'Rust'], runtimePlatform: 'Node.js >= 22.13', license: `${repo}/blob/main/LICENSE`, targetProduct: { '@id': `${siteUrl}/#app` }, author: { '@id': `${siteUrl}/#maintainer` } },
    { '@type': 'FAQPage', '@id': `${canonical}#faq`, url: `${canonical}#faq`, inLanguage: t.lang, isPartOf: { '@id': `${canonical}#webpage` }, mainEntity: t.faqs.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) },
  ] };
  return `<!DOCTYPE html>
<html lang="${t.lang}">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(t.title)}</title><meta name="description" content="${esc(t.description)}"><meta name="robots" content="index, follow">
  <meta name="author" content="${maintainer.name}">${Object.entries(siteVerification).map(([name, value]) => `<meta name="${name}" content="${value}">`).join('')}<link rel="canonical" href="${canonical}">${hreflangLinks()}
  <meta property="og:type" content="website"><meta property="og:site_name" content="${esc(t.siteName)}"><meta property="og:locale" content="${meta.ogLocale}">${Object.entries(locales).filter(([key]) => key !== locale).map(([, item]) => `<meta property="og:locale:alternate" content="${item.ogLocale}">`).join('')}<meta property="og:title" content="${esc(t.title)}"><meta property="og:description" content="${esc(t.description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${ogImage}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${esc(t.ogAlt)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(t.title)}"><meta name="twitter:description" content="${esc(t.description)}"><meta name="twitter:image" content="${ogImage}"><meta name="twitter:image:alt" content="${esc(t.ogAlt)}">
  <link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/style.css">
  <script type="application/ld+json">${JSON.stringify(jsonld).replace(/</g, '\\u003c')}</script>
  <script src="/app.js" defer></script>
  <script src="/signal-field.js" defer></script>
  <script id="demoData" type="application/json">${JSON.stringify({ text: t, agents, samples }).replace(/</g, '\\u003c')}</script>
</head>
<body data-locale="${locale}">
  <a class="skip-link" href="#main">${t.skip}</a>
  <div class="site-content">
    <main id="main">
      <section class="signal-hero" aria-labelledby="hero-title">
        <canvas id="signalCanvas" aria-hidden="true"></canvas>
        <header class="site-topbar"><a class="brand" href="${meta.path}"><img class="brand-mark" src="/watch-mark.svg" alt="" width="30" height="15">Watch<span> / 值更</span></a><nav id="siteNav" aria-label="${t.workspace}">${nav.slice(0, 4).map(([id, name, text]) => `<a href="#${id}" class="nav-item"><span>${text}</span></a>`).join('')}</nav><div class="topbar-actions"><a href="${locales[other].path}" class="language-link" lang="${locales[other].hreflang}" hreflang="${locales[other].hreflang}">${t.language}</a>${link(repo, 'GitHub')}<a class="nav-start" href="#quickstart">${t.start}</a><button class="icon-button mobile-menu" id="menuButton" aria-label="${t.menu}" aria-expanded="false" aria-controls="siteNav">${icon('menu')}</button></div><span id="currentSection" class="sr-only">${t.demo}</span></header>
        <div class="hero-content"><p class="eyebrow">${t.heroLabel}</p><h1 id="hero-title">${esc(t.h1)}<span class="h1-sub">${esc(t.h1Sub)}</span></h1><p class="hero-tagline">${t.intro}</p><p class="hero-detail">${t.heroDetail}</p><div class="hero-actions"><a href="#quickstart" class="primary-button">${t.start}${icon('arrow-up-right')}</a><a href="#simulator" class="secondary-button">${t.explore}${icon('arrow-right')}</a></div></div>
        <div class="hero-bottom"><span>CLAUDE / CODEX / OPENCODE / KIMI / PI</span><a href="#simulator">${t.scroll}${icon('arrow-down')}</a><span>MIT / v0.1.1</span></div>
      </section>
      <section id="simulator" class="site-section demo-section">
        <div class="page-heading"><div><span class="eyebrow">01 / SESSION CONTINUITY</span><h2>${t.demo}</h2><p>${t.introDetail}</p></div><span class="environment-label"><i class="status-dot"></i>${t.demoBadge}</span></div>
        <div class="workflow-strip">${t.stepLabels.map((label, index) => `<div class="workflow-item" data-step="${index}"><span class="step-index">0${index + 1}</span><span>${label}</span>${index < 3 ? icon('arrow-right') : ''}</div>`).join('')}</div>
        <div class="demo-workspace">
          <div class="source-column"><div class="section-heading"><h2>${t.source}</h2><span>01 / SOURCE</span></div>
            <label class="field-label" for="sampleSelect">${t.sample}</label><select id="sampleSelect">${t.sampleNames.map((name, index) => `<option value="${index}">${name}</option>`).join('')}</select>
            <label class="field-label" for="sessionIdInput">${t.sessionId}</label><div class="session-search">${icon('search')}<input id="sessionIdInput" value="11111111-1111-4111-8111-111111111111" spellcheck="false" autocomplete="off"><button class="icon-button" id="resetDemo" title="${t.reset}" aria-label="${t.reset}">${icon('refresh-cw')}</button></div>
            <div class="source-identity"><img id="sourceIcon" src="/agents/claude.svg" alt=""><strong id="detectedAgent">Claude Code</strong><span class="badge blue">${t.online}</span></div>
            <div class="cwd-row">${icon('folder')}<code id="detectedCwd">/Users/dev/projects/example-api</code></div>
            <dl class="sample-metrics"><div><dt>${t.messages}</dt><dd id="detectedMessages">24</dd></div><div><dt>${t.tools}</dt><dd id="detectedTools">8</dd></div><div><dt>${t.status}</dt><dd class="text-metric" id="sourceStatus">${t.loaded}</dd></div></dl>
            <div class="context-section"><div class="section-heading"><h3>${t.context}</h3><span>SNAPSHOT</span></div><div class="excerpt-row"><span class="role-label">${t.user}</span><p>${t.userPrompt}</p></div><div class="excerpt-row"><span class="role-label blue">${t.assistant}</span><p>${t.assistantReply}</p></div><div class="tool-list"><span>TOOLS</span><code>Bash</code><code>Edit</code><code>Read</code></div></div>
          </div>
          <div class="target-column"><div class="section-heading"><h2>${t.target}</h2><span>02 / TARGET</span></div><div class="agent-selector" role="radiogroup" aria-label="${t.target}">${agents.map((agent) => `<button class="agent-option ${agent.id === 'codex' ? 'selected' : ''}" role="radio" aria-checked="${agent.id === 'codex'}" data-target="${agent.id}"><img src="/agents/${agent.id}.svg" alt=""><span>${agent.label}</span><span class="radio-indicator"></span></button>`).join('')}</div>
            <div class="handoff-tool"><div class="handoff-tool-heading"><span class="route-label">${icon('workflow')}<strong id="routeLabel">${t.official}</strong></span><span class="badge">DEMO</span></div><div class="handoff-tool-body"><p class="route-description" id="routeWarning">${t.officialWarning}</p><div class="delivery-row"><span>${t.delivery}</span><div class="segmented" role="group" aria-label="${t.delivery}"><button data-client="desktop" class="active">${icon('monitor')}${t.desktop}</button><button data-client="terminal">${icon('terminal')}${t.terminal}</button></div></div><div id="demoPlan" class="demo-plan" hidden><span>${t.planLabel}</span><code id="planId">demo-plan / example-api</code></div><div class="demo-actions"><button id="previewButton" class="primary-button">${t.preview}${icon('arrow-right')}</button><button id="confirmButton" class="primary-button" hidden>${t.confirm}${icon('check')}</button><button id="openButton" class="primary-button" hidden>${t.open}${icon('arrow-up-right')}</button><button id="restartButton" class="text-button">${icon('refresh-cw')}${t.reset}</button></div></div></div>
          </div>
        </div>
        <div class="demo-result"><div class="result-topline"><h2>${t.result}</h2><span id="pipelineStatus" class="badge">${t.waiting}</span></div><div class="result-tabs" role="tablist" aria-label="${t.result}"><button id="logsTab" role="tab" aria-selected="true" aria-controls="simLogs">${icon('list-checks')}${t.logs}</button><button id="structureTab" role="tab" aria-selected="false" aria-controls="simAst">${icon('code')}${t.structure}</button></div><div id="simLogs" role="tabpanel" aria-labelledby="logsTab" class="sim-log" aria-live="polite"><p>${t.logReady}</p></div><div id="simAst" role="tabpanel" aria-labelledby="structureTab" class="event-comparison" hidden><div><span>${t.eventSource}</span><pre id="sourceEvent"></pre></div><div><span>${t.eventTarget}</span><pre id="targetEvent"></pre></div></div><div class="command-output" id="commandOutput" hidden><span>$</span><code id="targetCommand"></code><button class="icon-button" id="copyTarget" title="${t.copy}" aria-label="${t.copy}">${icon('copy')}</button></div></div>
        <p class="demo-disclaimer">${icon('info')}${t.demoNotice}</p>
      </section>
      <section id="features" class="site-section"><div class="section-title"><span class="eyebrow">UNDER THE HOOD</span><h2>${t.mechanisms}</h2><p>${t.mechanismIntro}</p></div><div class="mechanism-grid">${t.mechanismItems.map(([name, title, body], index) => `<article class="mechanism-item"><span class="mechanism-icon">${icon(name)}</span><span class="item-index">0${index + 1}</span><h3>${title}</h3><p>${body}</p></article>`).join('')}</div></section>
      <section id="compatibility" class="site-section"><div class="section-title"><span class="eyebrow">ROUTE-SCOPED VALIDATION</span><h2>${t.compatibility}</h2><p>${t.compatibilityIntro}</p></div><div class="filter-bar" role="group" aria-label="${t.compatibility}">${[['all', t.all], ['limited', t.limited], ['pending', t.pending]].map(([value, label]) => `<button class="filter-button ${value === 'all' ? 'active' : ''}" data-filter="${value}" aria-pressed="${value === 'all'}">${label}</button>`).join('')}<span>2026-09-10 / REPOSITORY</span></div><div class="table-scroll"><table class="compat-table"><thead><tr><th>${t.path}</th><th>${t.method}</th><th>${t.scope}</th><th>${t.status}</th></tr></thead><tbody>${t.paths.map(([route, method, scope, category, status]) => `<tr data-category="${category}"><td>${route}</td><td>${method}</td><td>${scope}</td><td><span class="badge ${category === 'limited' ? 'green' : 'amber'}">${status}</span></td></tr>`).join('')}</tbody></table></div><div class="section-bottom-link">${link(`${repo}/blob/main/docs/COMPATIBILITY.md`, 'COMPATIBILITY.md')}</div></section>
      <section id="quickstart" class="site-section"><div class="section-title"><span class="eyebrow">DEVELOPER WORKFLOW</span><h2>${t.quickstart}</h2><p>${t.quickIntro}</p></div><div class="quickstart-heading"><div class="segmented" role="tablist" aria-label="${t.quickstart}"><button id="cliTab" role="tab" aria-selected="true" aria-controls="cliCommands" data-quick="cli" class="active">${icon('terminal')}${t.cli}</button><button id="desktopTab" role="tab" aria-selected="false" aria-controls="desktopCommands" data-quick="desktop">${icon('monitor')}${t.desktopBuild}</button></div><span class="requirements">${t.requirements}</span></div>${Object.entries(commands).map(([key, list]) => `<div id="${key}Commands" class="command-list" role="tabpanel" aria-labelledby="${key === 'cli' ? 'cliTab' : 'desktopTab'}" ${key === 'desktop' ? 'hidden' : ''}>${list.map((command) => `<div class="command-row"><span>$</span><code>${esc(command)}</code><button class="icon-button" data-copy="${esc(command)}" title="${t.copy}" aria-label="${t.copy}">${icon('copy')}</button></div>`).join('')}<button class="text-button copy-group" data-copy="${esc(list.join('\n'))}">${icon('copy')}${t.copyAll}</button></div>`).join('')}<p class="troubleshooting">${icon('info')}${t.troubleshooting}</p></section>
      <section id="media" class="site-section"><div class="section-title"><span class="eyebrow">REAL OUTPUT / SYNTHETIC SESSIONS</span><h2>${t.media}</h2><p>${t.mediaIntro}</p></div><div class="media-grid"><figure><img src="/media/cli-claude-to-opencode.gif" alt="${esc(t.mediaItems[0][0])}" width="960" height="600" loading="lazy"><figcaption><strong>${esc(t.mediaItems[0][0])}</strong><span>${esc(t.mediaItems[0][1])}</span></figcaption></figure><figure><img src="/media/desktop-imported.png" alt="${esc(t.mediaItems[1][0])}" width="1400" height="1220" loading="lazy"><figcaption><strong>${esc(t.mediaItems[1][0])}</strong><span>${esc(t.mediaItems[1][1])}</span></figcaption></figure></div><div class="section-bottom-link">${link(`${repo}/blob/main/assets/README.md`, t.mediaMore)}</div></section>
      <section id="evidence" class="site-section"><div class="section-title"><span class="eyebrow">VERIFIABLE RECORDS</span><h2>${t.evidence}</h2><p>${t.evidenceIntro}</p></div><ol class="evidence-list">${evidence.map((item, index) => `<li><time datetime="${item.date}">${item.date}</time><div><h3>${t.evidenceTitles[index]}</h3><p>${t.evidenceDetails[index]}</p></div><span class="evidence-number">0${index + 1}</span></li>`).join('')}</ol></section>
      <section id="faq" class="site-section"><div class="section-title"><span class="eyebrow">QUESTIONS & BOUNDARIES</span><h2>${t.faq}</h2></div><div class="faq-list">${t.faqs.map(([question, answer]) => `<details><summary>${esc(question)}${icon('plus')}</summary><p>${esc(answer)}</p></details>`).join('')}</div></section>
      <section id="antigravity" class="site-section"><div class="section-title"><span class="eyebrow">OFFICIAL ENTRY / NOT INTEGRATED</span><h2>${t.antigravityTitle}</h2><p>${t.antigravityIntro}</p></div><p class="antigravity-status">${icon('info')}${t.antigravityStatus}</p><div class="antigravity-list">${t.antigravityItems.map(([title, command, detail], index) => `<article><span class="item-index">0${index + 1}</span><h3>${esc(title)}</h3><code>${esc(command)}</code><p>${esc(detail)}</p></article>`).join('')}</div><div class="antigravity-links">${link('https://antigravity.google/docs/cli/commands/resume', t.antigravityDocs)}</div></section>
    </main>
    <footer class="site-footer"><div class="footer-main"><div><strong>Watch · 值更</strong><p>${t.footerNote}</p></div><div><span class="nav-caption">${t.fleet}</span>${['Homeport', 'Watch', 'Atlas', 'Sonar', 'Semaphore'].map((name) => link(`https://github.com/can4hou6joeng4/${name}`, name)).join('')}</div><div><span class="nav-caption">${t.docs}</span>${link(`${repo}#readme`, 'README')}${link(`${repo}/blob/main/docs/import-codex.md`, 'Codex Import')}${link(`${repo}/blob/main/docs/ARCHITECTURE.md`, 'Architecture')}<a href="/sitemap.xml">Sitemap</a><a href="/robots.txt">Robots</a></div></div><div class="footer-bottom"><span>© 2026 can4hou6joeng4 · ${t.license}</span><span>${t.updated} / v0.1.1</span></div></footer>
  </div><div id="copyToast" class="copy-toast" role="status" aria-live="polite" hidden>${icon('check')}<span id="toastMessage"></span></div>
  <noscript><p class="noscript-note">${t.demoNotice} JavaScript is required for the synthetic demo. All project information is available below.</p></noscript>
</body></html>`;
}

const require = createRequire(path.join(root, 'desktop/package.json'));
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const lucide = require('lucide-react');
const names = ['Workflow', 'ArrowUpRight', 'ArrowRight', 'ArrowDown', 'Layers', 'ShieldCheck', 'Terminal', 'History', 'CircleHelp', 'Menu', 'Languages', 'Search', 'RefreshCw', 'Folder', 'Monitor', 'Check', 'ListChecks', 'Code', 'Copy', 'Info', 'Plus', 'FileText'];
const toId = (name) => name.replace(/[A-Z]/g, (char, index) => `${index ? '-' : ''}${char.toLowerCase()}`);
const sprite = `<svg xmlns="http://www.w3.org/2000/svg"><defs>${names.map((name) => renderToStaticMarkup(React.createElement(lucide[name], { id: toId(name), width: 24, height: 24, strokeWidth: 1.7 }))).join('')}</defs></svg>`;
fs.mkdirSync(path.join(site, 'agents'), { recursive: true });
for (const agent of agents) fs.copyFileSync(path.join(root, `desktop/public/${agent.id}.svg`), path.join(site, `agents/${agent.id}.svg`));
fs.writeFileSync(path.join(site, 'icons.svg'), sprite);
fs.copyFileSync(path.join(site, 'input.css'), path.join(site, 'style.css'));
for (const [locale, meta] of Object.entries(locales)) {
  const dir = path.join(site, meta.path);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), renderPage(locale));
}
const notFound = Object.entries(locales).map(([locale, meta]) => { const t = content[locale]; return `<section lang="${meta.hreflang}"><span class="eyebrow">404 / NOT FOUND</span><h1>${t.notFound}</h1><p>${t.notFoundText}</p><a href="${meta.path}" class="primary-button">${t.back}${icon('arrow-right')}</a></section>`; }).join('');
fs.writeFileSync(path.join(site, '404.html'), `<!DOCTYPE html><html lang="${locales.zh.hreflang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>404 · Watch</title><link rel="stylesheet" href="/style.css"><link rel="icon" href="/favicon.svg"></head><body class="not-found"><a class="brand" href="/"><img class="brand-mark" src="/watch-mark.svg" alt="" width="30" height="15">Watch</a><main>${notFound}</main></body></html>`);
const sitemapEntry = (locale) => `  <url>\n    <loc>${localeUrl(locale)}</loc>\n    <lastmod>${siteDate}</lastmod>\n${Object.entries(locales).map(([key, meta]) => `    <xhtml:link rel="alternate" hreflang="${meta.hreflang}" href="${localeUrl(key)}" />`).join('\n')}\n    <xhtml:link rel="alternate" hreflang="x-default" href="${localeUrl(defaultLocale)}" />\n  </url>`;
fs.writeFileSync(path.join(site, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${Object.keys(locales).map(sitemapEntry).join('\n')}\n</urlset>\n`);
const headers = fs.readFileSync(path.join(site, '_headers'), 'utf8').split(/\n(?=\/)/).filter((block) => !/^\/[a-z-]+\/\*\n  ! Content-Language/.test(block)).join('\n').trimEnd();
fs.writeFileSync(path.join(site, '_headers'), `${headers}\n${Object.entries(locales).filter(([locale]) => locales[locale].path !== '/').map(([, meta]) => `\n${meta.path}*\n  ! Content-Language\n  Content-Language: ${meta.hreflang}`).join('')}\n`);
console.log('Generated Chinese / English pages, 404, shared CSS, Lucide sprites and provider assets.');
